version: '3.3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=redis://redis
      - PORT=3000
      - MONGODB_URI=mongodb://mongo/purls
    ports:
      - 3000:3000
    volumes:
      - .:/opt/purls
    links:
      - redis
      - mongo
    command: /usr/local/wait-for-it.sh mongo:27017 redis:6379 -- yarn dev
    tty: true

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data/redis
